server:
  port: 0

spring:
  application:
    name: class-service

  datasource:
    url: "jdbc:sqlite::memory:"
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
